name: Submission
on: pull_request
jobs: 
  one:
    # Only run the action against the base repo 
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Update Challenge Status
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Setup Postgresql
        run: sudo apt-get -yqq install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create Database
        run: |
          RAILS_ENV=test
          bundler exec rails db:create
          bundler exec rails db:migrate
      - name: Run RSpec tests
        run: bin/rspec
      - if: job.status == failure
        uses: wei/curl@v1 
        with:
          args: '-X PATCH -H ''Authorization: Token ${{ secrets.ACTION_TOKEN }}'' ''https://quiet-taiga-51315.herokuapp.com/challenge_attempts/1?student=${{ github.actor }}&challenge=${{ github.repository }}&status=attempted'''
      - if: job.status == success
        uses: wei/curl@v1 
        with:
          args: '-X PATCH -H ''Authorization: Token ${{ secrets.ACTION_TOKEN }}'' ''https://quiet-taiga-51315.herokuapp.com/challenge_attempts/1?student=${{ github.actor }}&challenge=${{ github.repository }}&status=attempted'''



